### ISSUE TITLE
OapFileFormat Errs exposed From the Daylitest for OAP 0.6

### ISSUE THREAD

**Issue by zhixingheyi-tian** [Intel-bigdata/OAP#1006]
case:  "SELECT * FROM  oap_tpcds.store_sales limit 10"

## First err
```
19/01/25 18:09:47 ERROR SparkSQLDriver: Failed in [SELECT * FROM  200oap_tpcds_200.store_sales limit 10]
scala.MatchError: null
	at org.apache.spark.sql.execution.datasources.oap.OapFileFormat.buildReaderWithPartitionValues(OapFileFormat.scala:153)
	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD$lzycompute(DataSourceScanExec.scala:308)
	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD(DataSourceScanExec.scala:297)
	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDDs(DataSourceScanExec.scala:326)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:605)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)

```
## second err
OapFileFormat.scala:153:
```
    meta match {
      case Some(m) =>
       ...
       case None => (_: PartitionedFile) => {
        // TODO need to think about when there is no oap.meta file at all
        Iterator.empty
      }
```

Change "case None" to "case _" and the error disappears.
However, the amount of data is displayed as 0.
```
SELECT count(1) FROM  200oap_tpcds_200.store_sales
0
Time taken: 0.367 seconds, Fetched 1 row(s)
```
Actually there is data in the table. If in the Spark 2.3. can query the data.

**Comment by LuciferYang** [comment]
How can we reproduce this problem?

**Comment by LuciferYang** [comment]
maybe we need add "spark.sql.extensions org.apache.spark.sql.OapExtensions" to spark-default.conf

**Comment by zhixingheyi-tian** [comment]
@LuciferYang 
You are right.
Perhaps, later, OAP fileFormat should work like Paquet，Orc, without spark.sql.extensions conf item.

**Comment by LuciferYang** [comment]
@zhixingheyi-tian 
Agree with u, now `OapFileFormat` needs to call the `init` method to work,  we need to improve it.

**Comment by agaszmurlo** [comment]
Hi, 

I have used OAP on YARN and encountered this issue (scala.MatchError: null) as well as catalyst complaining it doesn't support DDL statement for creating indexes. 

Your suggestion to add spark.sql.extensions org.apache.spark.sql.OapExtensions to spark-default.conf fixed both those issues. I think you should add this to recommended configuration in user guide.

**Comment by LuciferYang** [comment]
@agaszmurlo thx for ur feedback, @zhixingheyi-tian we should add `spark.sql.extensions org.apache.spark.sql.OapExtensions` to our user guide
