### ISSUE TITLE
Binary cache IllegalArgumentException issue

### ISSUE THREAD

**Issue by jikunshang** [Intel-bigdata/OAP#1387]
I am using parquet binary cache and run TPC-DS 99 queries,  some queries will throw such error: 

**_java.lang.IllegalArgumentException: FilterPredicate column: cs_ext_discount_amt's declared type (java.lang.Integer) does not match the schema found in file metadata. Column cs_ext_discount_amt is of type: FIXED_LEN_BYTE_ARRAY
Valid types for this column are: [class org.apache.parquet.io.api.Binary]**
        at org.apache.parquet.filter2.predicate.ValidTypeMap.assertTypeValid(ValidTypeMap.java:126)
        at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.validateColumn(SchemaCompatibilityValidator.java:181)
        at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.validateColumnFilterPredicate(SchemaCompatibilityValidator.java:151)
        at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:91)
        at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:58)
        at org.apache.parquet.filter2.predicate.Operators$NotEq.accept(Operators.java:195)
        at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:122)
        at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:58)
        at org.apache.parquet.filter2.predicate.Operators$And.accept(Operators.java:309)
        at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:121)
        at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:58)
        at org.apache.parquet.filter2.predicate.Operators$And.accept(Operators.java:309)
        at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.validate(SchemaCompatibilityValidator.java:63)
        at org.apache.parquet.filter2.compat.RowGroupFilter.visit(RowGroupFilter.java:92)
        at org.apache.parquet.filter2.compat.RowGroupFilter.visit(RowGroupFilter.java:43)
        at org.apache.parquet.filter2.compat.FilterCompat$FilterPredicateCompat.accept(FilterCompat.java:137)
        at org.apache.parquet.filter2.compat.RowGroupFilter.filterRowGroups(RowGroupFilter.java:69)
        at org.apache.parquet.hadoop.ParquetFileReader.filterRowGroups(ParquetFileReader.java:752)
        at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:679)
        at org.apache.parquet.hadoop.ParquetCacheableFileReader.<init>(ParquetCacheableFileReader.java:64)
        at org.apache.parquet.hadoop.OapParquetFileReader.open(OapParquetFileReader.java:47)
        at org.apache.parquet.hadoop.SpecificOapRecordReaderBase.initialize(SpecificOapRecordReaderBase.java:71)
        at org.apache.parquet.hadoop.VectorizedOapRecordReader.initialize(VectorizedOapRecordReader.java:156)
        at org.apache.spark.sql.execution.datasources.oap.io.ParquetDataFile.initVectorizedReader(ParquetDataFile.scala:183)
        at org.apache.spark.sql.execution.datasources.oap.io.ParquetDataFile.iterator(ParquetDataFile.scala:124)
        at org.apache.spark.sql.execution.datasources.oap.io.OapDataReaderV1.fullScan$1(OapDataReaderWriter.scala:230)
        at org.apache.spark.sql.execution.datasources.oap.io.OapDataReaderV1.initialize(OapDataReaderWriter.scala:289)
        at org.apache.spark.sql.execution.datasources.oap.io.OapDataReaderV1.read(OapDataReaderWriter.scala:299)
        at org.apache.spark.sql.execution.datasources.oap.OptimizedParquetFileFormat$$anonfun$buildReaderWithPartitionValues$2.apply(OptimizedParquetFileFormat.scala:124)
        at org.apache.spark.sql.execution.datasources.oap.OptimizedParquetFileFormat$$anonfun$buildReaderWithPartitionValues$2.apply(OptimizedParquetFileFormat.scala:110)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:124)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:177)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:101)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.scan_nextBatch_0$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)_

**And I notice that queies contain ‘cs_ext_discount_amt’ column will fail, you can run query 88 to reproduce it.**

query 88:
with ss as (
 select
          i_item_id,sum(ss_ext_sales_price) total_sales
 from
        store_sales,
        date_dim,
         customer_address,
         item
 where
         i_item_id in (select
  i_item_id
from
 item
where i_category in ('Men'))
 and     ss_item_sk              = i_item_sk
 and     ss_sold_date_sk         = d_date_sk
 and     d_year                  = 2001
 and     d_moy                   = 10
 and     ss_addr_sk              = ca_address_sk
 and     ca_gmt_offset           = -8
 group by i_item_id),
 cs as (
 select
          i_item_id,sum(cs_ext_sales_price) total_sales
 from
        catalog_sales,
        date_dim,
         customer_address,
         item
 where
         i_item_id               in (select
  i_item_id
from
 item
where i_category in ('Men'))
 and     cs_item_sk              = i_item_sk
 and     cs_sold_date_sk         = d_date_sk
 and     d_year                  = 2001
 and     d_moy                   = 10
 and     cs_bill_addr_sk         = ca_address_sk
 and     ca_gmt_offset           = -8
 group by i_item_id),
 ws as (
 select
          i_item_id,sum(ws_ext_sales_price) total_sales
 from
        web_sales,
        date_dim,
         customer_address,
         item
 where
         i_item_id               in (select
  i_item_id
from
 item
where i_category in ('Men'))
 and     ws_item_sk              = i_item_sk
 and     ws_sold_date_sk         = d_date_sk
 and     d_year                  = 2001
 and     d_moy                   = 10
 and     ws_bill_addr_sk         = ca_address_sk
 and     ca_gmt_offset           = -8
 group by i_item_id)
  select
  i_item_id
,sum(total_sales) total_sales
 from  (select * from ss
        union all
        select * from cs
        union all
        select * from ws) tmp1
 group by i_item_id
 order by i_item_id
      ,total_sales
 limit 100;

**Comment by zhixingheyi-tian** [comment]
cc @LuciferYang @lidinghao

**Comment by LuciferYang** [comment]
A little strange because we already successfully completed 99 tpc-ds queries in our test environment, but we're going to focus on this problem ~ @zhixingheyi-tian

**Comment by LuciferYang** [comment]
@zhixingheyi-tian How do we write parquet data ?  If we write parquet file with `PARQUET_WRITE_LEGACY_FORMAT`, maybe we should not push down Decimal filters.

```
  val PARQUET_WRITE_LEGACY_FORMAT = buildConf("spark.sql.parquet.writeLegacyFormat")
    .doc("If true, data will be written in a way of Spark 1.4 and earlier. For example, decimal " +
      "values will be written in Apache Parquet's fixed-length byte array format, which other " +
      "systems such as Apache Hive and Apache Impala use. If false, the newer format in Parquet " +
      "will be used. For example, decimals will be written in int-based format. If Parquet " +
      "output is intended for use with systems that do not support this newer format, set to true.")
    .booleanConf
    .createWithDefault(false)
```

But OptimizedParquetFileFormat is not support config  this option now,  we need check-pick [SPARK-24718](https://github.com/apache/spark/pull/21741/files)

**Comment by jikunshang** [comment]
> @zhixingheyi-tian How do we write parquet data ? If we write parquet file with `PARQUET_WRITE_LEGACY_FORMAT`, maybe we should not push down Decimal filters.
> 
> ```
>   val PARQUET_WRITE_LEGACY_FORMAT = buildConf("spark.sql.parquet.writeLegacyFormat")
>     .doc("If true, data will be written in a way of Spark 1.4 and earlier. For example, decimal " +
>       "values will be written in Apache Parquet's fixed-length byte array format, which other " +
>       "systems such as Apache Hive and Apache Impala use. If false, the newer format in Parquet " +
>       "will be used. For example, decimals will be written in int-based format. If Parquet " +
>       "output is intended for use with systems that do not support this newer format, set to true.")
>     .booleanConf
>     .createWithDefault(false)
> ```
> 
> But OptimizedParquetFileFormat is not support config this option now, we need check-pick [SPARK-24718](https://github.com/apache/spark/pull/21741/files)

Yes, we set 'spark.sql.parquet.writeLegacyFormat = true' when generate data(write parquet file). It will not reproduce in another environment without this conf.
Thanks a lot for your support . Will close this issue.
