### ISSUE TITLE
ERROR scheduler.TaskSetManager: Task 0 in stage 1.0 failed 4 times; aborting job

### ISSUE THREAD

**Issue by Lizf-0308** [Intel-bigdata/OAP#1540]
Hello,
I have met some problems while testing RPmem shuffle extension with Hibench 7.0 TeraSort. Could you please give me some help?
I have setup three nodes for spark-2.4.4-bin-hadoop2.7 and hadoop-2.7.3 on CentOS 7.0 x86 servers. 
And I compiled and installed OAP according to your guide document [Shuffle Remote PMem Extension](https://github.com/Intel-bigdata/OAP/blob/master/oap-shuffle/RPMem-shuffle/README.md). 

Follow is my Configuration:
- Genuine Intel(R) CPU, 192GB Memory (12x 16GB 2666MT/s)
- Mellanox ConnectX-5 100Gb NIC with ofed driver MLNX_OFED_LINUX-4.7-3.2.9.0
- 4x 128GB Persistent Memory for shuffle
- Software versions
  Hadoop 2.7.3, 
  Spark 2.4.4,
  scala-2.11.12,
  OpenJDK 1.8.0_181,
  BKC: fw_ekvb0_1.2.0.5310_encrypt_signed_strip (It's an early version)
- Compile branchs
  libfabric v1.6.0, HPNL origin/spark-pmof-test, ndctl v63, PMDK tags/1.8, OAP v0.8.1-spark-2.4.4

I'm sure my physical RDMA is ok. And I created one namespace on region0 each node.

The issue is:
**bench.log**
...
20/07/28 20:23:42 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 3072 ms on 10.10.10.103 (executor 0) (6/8)
20/07/28 20:23:42 INFO scheduler.TaskSetManager: Finished task 2.0 in stage 0.0 (TID 2) in 3045 ms on 10.10.10.103 (executor 0) (7/8)
20/07/28 20:23:42 INFO scheduler.TaskSetManager: Finished task 5.0 in stage 0.0 (TID 5) in 3043 ms on 10.10.10.103 (executor 0) (8/8)
20/07/28 20:23:42 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
20/07/28 20:23:42 INFO scheduler.DAGScheduler: ResultStage 0 (BaseRangePartitioner at ScalaTeraSort.scala:56) finished in 4.196 s
20/07/28 20:23:42 INFO scheduler.DAGScheduler: Job 0 finished: BaseRangePartitioner at ScalaTeraSort.scala:56, took 4.285363 s
20/07/28 20:23:42 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 1
20/07/28 20:23:42 INFO spark.SparkContext: Starting job: runJob at SparkHadoopWriter.scala:78
20/07/28 20:23:42 INFO scheduler.DAGScheduler: Registering RDD 1 (map at ScalaTeraSort.scala:49)
20/07/28 20:23:42 INFO scheduler.DAGScheduler: Got job 1 (runJob at SparkHadoopWriter.scala:78) with 8 output partitions
20/07/28 20:23:42 INFO scheduler.DAGScheduler: Final stage: ResultStage 2 (runJob at SparkHadoopWriter.scala:78)
20/07/28 20:23:42 INFO scheduler.DAGScheduler: Parents of final stage: List(ShuffleMapStage 1)
20/07/28 20:23:42 INFO scheduler.DAGScheduler: Missing parents: List(ShuffleMapStage 1)
20/07/28 20:23:42 INFO scheduler.DAGScheduler: Submitting ShuffleMapStage 1 (MapPartitionsRDD[1] at map at ScalaTeraSort.scala:49), which has no missing parents
20/07/28 20:23:43 INFO memory.MemoryStore: Block broadcast_2 stored as values in memory (estimated size 4.3 KB, free 5.2 GB)
20/07/28 20:23:43 INFO memory.MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 2.7 KB, free 5.2 GB)
20/07/28 20:23:43 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on spark01:34032 (size: 2.7 KB, free: 5.2 GB)
20/07/28 20:23:43 INFO spark.SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1161
20/07/28 20:23:43 INFO scheduler.DAGScheduler: Submitting 8 missing tasks from ShuffleMapStage 1 (MapPartitionsRDD[1] at map at ScalaTeraSort.scala:49) (first 15 tasks are for partitions Vector(0, 1, 2, 3, 4, 5, 6, 7))
20/07/28 20:23:43 INFO scheduler.TaskSchedulerImpl: Adding task set 1.0 with 8 tasks
20/07/28 20:23:43 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 1.0 (TID 8, 10.10.10.103, executor 0, partition 0, ANY, 7950 bytes)
20/07/28 20:23:43 INFO scheduler.TaskSetManager: Starting task 1.0 in stage 1.0 (TID 9, 10.10.10.101, executor 1, partition 1, ANY, 7950 bytes)
20/07/28 20:23:43 INFO scheduler.TaskSetManager: Starting task 2.0 in stage 1.0 (TID 10, 10.10.10.103, executor 0, partition 2, ANY, 7950 bytes)
20/07/28 20:23:43 INFO scheduler.TaskSetManager: Starting task 3.0 in stage 1.0 (TID 11, 10.10.10.101, executor 1, partition 3, ANY, 7950 bytes)
20/07/28 20:23:43 INFO scheduler.TaskSetManager: Starting task 4.0 in stage 1.0 (TID 12, 10.10.10.103, executor 0, partition 4, ANY, 7950 bytes)
20/07/28 20:23:43 INFO scheduler.TaskSetManager: Starting task 5.0 in stage 1.0 (TID 13, 10.10.10.101, executor 1, partition 5, ANY, 7950 bytes)
20/07/28 20:23:43 INFO scheduler.TaskSetManager: Starting task 6.0 in stage 1.0 (TID 14, 10.10.10.103, executor 0, partition 6, ANY, 7950 bytes)
20/07/28 20:23:43 INFO scheduler.TaskSetManager: Starting task 7.0 in stage 1.0 (TID 15, 10.10.10.101, executor 1, partition 7, ANY, 7950 bytes)
20/07/28 20:23:43 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on 10.10.10.103:42649 (size: 2.7 KB, free: 7.8 GB)
20/07/28 20:23:43 WARN scheduler.TaskSetManager: Lost task 4.0 in stage 1.0 (TID 12, 10.10.10.103, executor 0): java.util.NoSuchElementException: key not found: 10.10.10.103
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
        at org.apache.spark.network.pmof.PmofTransferService$.getTransferServiceInstance(PmofTransferService.scala:93)
        at org.apache.spark.shuffle.pmof.PmofShuffleManager.getWriter(PmofShuffleManager.scala:46)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:98)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
20/07/28 20:23:44 INFO scheduler.TaskSetManager: Lost task 7.0 in stage 1.0 (TID 15) on 10.10.10.101, executor 1: java.util.NoSuchElementException (key not found: 10.10.10.101) [duplicate 1]
20/07/28 20:23:44 INFO scheduler.TaskSetManager: Lost task 0.3 in stage 1.0 (TID 21) on 10.10.10.101, executor 1: java.util.NoSuchElementException (key not found: 10.10.10.101) [duplicate 2]
20/07/28 20:23:44 ERROR scheduler.TaskSetManager: Task 0 in stage 1.0 failed 4 times; aborting job
20/07/28 20:23:44 INFO scheduler.TaskSetManager: Lost task 4.1 in stage 1.0 (TID 16) on 10.10.10.101, executor 1: java.util.NoSuchElementException (key not found: 10.10.10.101) [duplicate 3]
20/07/28 20:23:44 INFO scheduler.TaskSetManager: Lost task 2.1 in stage 1.0 (TID 17) on 10.10.10.101, executor 1: java.util.NoSuchElementException (key not found: 10.10.10.101) [duplicate 4]
20/07/28 20:23:44 INFO scheduler.TaskSetManager: Lost task 6.1 in stage 1.0 (TID 19) on 10.10.10.101, executor 1: java.util.NoSuchElementException (key not found: 10.10.10.101) [duplicate 5]
20/07/28 20:23:44 INFO scheduler.TaskSetManager: Lost task 5.0 in stage 1.0 (TID 13) on 10.10.10.101, executor 1: java.util.NoSuchElementException (key not found: 10.10.10.101) [duplicate 6]
20/07/28 20:23:44 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool
20/07/28 20:23:44 INFO scheduler.TaskSetManager: Lost task 1.0 in stage 1.0 (TID 9) on 10.10.10.101, executor 1: java.util.NoSuchElementException (key not found: 10.10.10.101) [duplicate 7]
20/07/28 20:23:44 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool
20/07/28 20:23:44 INFO scheduler.TaskSchedulerImpl: Cancelling stage 1
20/07/28 20:23:44 INFO scheduler.TaskSchedulerImpl: Killing all running tasks in stage 1: Stage cancelled
20/07/28 20:23:44 INFO scheduler.DAGScheduler: ShuffleMapStage 1 (map at ScalaTeraSort.scala:49) failed in 1.778 s due to Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 21, 10.10.10.101, executor 1): java.util.NoSuchElementException: key not found: 10.10.10.101
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
        at org.apache.spark.network.pmof.PmofTransferService$.getTransferServiceInstance(PmofTransferService.scala:93)
        at org.apache.spark.shuffle.pmof.PmofShuffleManager.getWriter(PmofShuffleManager.scala:46)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:98)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Driver stacktrace:
20/07/28 20:23:44 INFO scheduler.DAGScheduler: Job 1 failed: runJob at SparkHadoopWriter.scala:78, took 1.986632 s
20/07/28 20:23:44 ERROR io.SparkHadoopWriter: Aborting job job_20200728202342_0006.
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 21, 10.10.10.101, executor 1): java.util.NoSuchElementException: key not found: 10.10.10.101
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
        at org.apache.spark.network.pmof.PmofTransferService$.getTransferServiceInstance(PmofTransferService.scala:93)
        at org.apache.spark.shuffle.pmof.PmofShuffleManager.getWriter(PmofShuffleManager.scala:46)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:98)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1876)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2110)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2114)
        at org.apache.spark.internal.io.SparkHadoopWriter$.write(SparkHadoopWriter.scala:78)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1083)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:1081)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:1081)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:1081)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply$mcV$sp(PairRDDFunctions.scala:1000)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:991)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:991)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:991)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:979)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$1.apply(PairRDDFunctions.scala:979)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$1.apply(PairRDDFunctions.scala:979)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:978)
        at com.intel.hibench.sparkbench.micro.ScalaTeraSort$.main(ScalaTeraSort.scala:60)
        at com.intel.hibench.sparkbench.micro.ScalaTeraSort.main(ScalaTeraSort.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
...More

**Comment by Lizf-0308** [comment]
@Jian-Zhang
