### ISSUE TITLE
[oap-native-sql] TPCH-Q7 fails in throughput tests

### ISSUE THREAD

**Issue by zhouyuan** [Intel-bigdata/OAP#1553]
This seems due to a wrongly generated join results 
```
Job aborted due to stage failure: Task 19 in stage 219.0 failed 4 times, most recent failure: Lost task 19.3 in stage 219.0 (TID 69701, sr242, executor 17): java.lang.IndexOutOfBoundsException: index: 0, length: 4096 (expected: range(0, 4040))
         at io.netty.buffer.ArrowBuf.checkIndex(ArrowBuf.java:718)
         at io.netty.buffer.ArrowBuf.setBytes(ArrowBuf.java:965)
         at org.apache.arrow.vector.BaseFixedWidthVector.reAlloc(BaseFixedWidthVector.java:439)
         at org.apache.arrow.vector.BaseFixedWidthVector.setValueCount(BaseFixedWidthVector.java:708)
         at org.apache.arrow.vector.VectorSchemaRoot.setRowCount(VectorSchemaRoot.java:230)
         at org.apache.arrow.vector.VectorLoader.load(VectorLoader.java:61)
         at com.intel.oap.vectorized.ArrowWritableColumnVector.loadColumns(ArrowWritableColumnVector.java:124)
         at com.intel.oap.expression.ConverterUtils$.fromArrowRecordBatch(ConverterUtils.scala:172)
         at com.intel.oap.expression.ColumnarShuffledHashJoin$$anon$2.next(ColumnarShuffledHashJoin.scala:145)
         at com.intel.oap.expression.ColumnarShuffledHashJoin$$anon$2.next(ColumnarShuffledHashJoin.scala:120)
         at com.intel.oap.vectorized.CloseableColumnBatchIterator.next(CloseableColumnBatchIterator.scala:54)
         at com.intel.oap.vectorized.CloseableColumnBatchIterator.next(CloseableColumnBatchIterator.scala:28)
         at com.intel.oap.expression.ColumnarConditionProjector$$anon$1.hasNext(ColumnarConditionProjector.scala:208)
         at com.intel.oap.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:49)
         at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:511)
         at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
         at org.apache.spark.sql.execution.CloseablePairedColumnarBatchIterator.hasNext(ColumnarShuffleExchangeExec.scala:347)
         at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:77)
         at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
         at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
         at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
         at org.apache.spark.scheduler.Task.run(Task.scala:127)
         at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
         at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
         at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at java.lang.Thread.run(Thread.java:748)
 
Driver stacktrace:

```

**Comment by xuechendi** [comment]
@zhouyuan , how to reproduce this error?

**Comment by xuechendi** [comment]
@zhouyuan , I felt https://github.com/Intel-bigdata/OAP/issues/1564 may be the same issue.
Seems there is an unknown memory issue.

**Comment by zhouyuan** [comment]
@xuechendi thanks for the look, i'll try to reproduce this on my throughput testing env

**Comment by zhouyuan** [comment]
fixed in master
