### ISSUE TITLE
[SQL Index and Data Source Cache] When index/data cache separation enables, DCPMM as cache media, vmem cache as index & data cache backend , queries failed.

### ISSUE THREAD

**Issue by HongW2019** [Intel-bigdata/OAP#1573]
```
#spark.sql.oap.fiberCache.memory.manager                 tmp
spark.sql.oap.index.data.cache.separation.enable        true
spark.oap.cache.strategy                                mix
spark.sql.oap.mix.data.cache.backend                    vmem
spark.sql.oap.mix.index.cache.backend                   vmem
spark.sql.oap.parquet.data.cache.enable                 true
spark.sql.oap.cache.guardian.memory.size                40g
```
When we use DCPMM as cache media , vmemcache as index & data cache backend, If not add `spark.sql.oap.fiberCache.memory.manager = tmp`, queries will fail like:

```
0: jdbc:hive2://vsr211:10000> ;Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 298.0 failed 4 times, most recent failure: Lost task 0.3 in stage 298.0 (TID 6695, vsr211, executor 2): java.lang.AssertionError: assertion failed: Failed to cache fiber(22.6 MB) with cache's MAX_WEIGHT(90.0 MB) / 4
        at scala.Predef$.assert(Predef.scala:170)
        at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache.get(OapCache.scala:723)
        at org.apache.spark.sql.execution.datasources.oap.filecache.MixCache.get(OapCache.scala:829)
        at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager.get(FiberCacheManager.scala:114)
        at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader$$anonfun$readNextRowGroup$3.apply(VectorizedCacheReader.scala:184)
        at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader$$anonfun$readNextRowGroup$3.apply(VectorizedCacheReader.scala:176)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader.readNextRowGroup(VectorizedCacheReader.scala:176)
        at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader.checkEndOfRowGroup(VectorizedCacheReader.scala:151)
        at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader.nextBatch(VectorizedCacheReader.scala:128)
        at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader.nextKeyValue(VectorizedCacheReader.scala:99)
        at org.apache.spark.sql.execution.datasources.oap.io.FileRecordReaderIterator.hasNext(DataFile.scala:66)
        at org.apache.spark.sql.execution.datasources.oap.io.OapCompletionIterator.hasNext(DataFile.scala:103)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:101)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:181)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:101)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.scan_nextBatch_0$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.agg_doAggregateWithKeys_0$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace: (state=,code=0)
```

**Comment by HongW2019** [comment]
@yma11  Is there something need to fix, cause when add `spark.sql.oap.fiberCache.memory.manager = tmp` , queries will run successfully.

**Comment by yma11** [comment]
@HongW2019 when use vmemcache, we have to set spark.sql.oap.fiberCache.memory.manager to tmp, this is expected so no fix need. Thanks.

**Comment by HongW2019** [comment]
@yma11 I remember you have simply this config, which will initialize memory manager"tmp" once use vmemcache since v0.7.0-spark-2.4.4, please check this, Thanks.

**Comment by yma11** [comment]
As synced, the root cause is that cachebackend is mix but memorymanager is not set to mix, so it will initialize memorymanager based on OAP_FIBERCACHE_MEMORY_MANAGER.key. Since it's not proper to set memorymanager to mix here, add "spark.sql.oap.fiberCache.memory.manager                 tmp" in conf can work.

**Comment by HongW2019** [comment]
@yma11 Thanks. We will add "spark.sql.oap.fiberCache.memory.manager tmp" in doc for this scenario in 0.8 , for further version,  maybe we'd better modify corresponding codes to be consistent with all scenarios in initializing `tmp`
