### ISSUE TITLE
[oap-native-sql] Error Native SQL with Thrift Server / spark.sql() works

### ISSUE THREAD

**Issue by rollandlee** [Intel-bigdata/OAP#1693]
### OAP-CACHE fully works

we downloaded the OAP 0.9 and installed through conda with hadoop 2.7 in our enviornment

whe we are testing it firstly with spark-shell & spark.sql, it works well

but when we are query it through Thrift server mode, it works with query with no aggregation function as:

```
select * from tbl_a
```
but if any aggr function added as 
```
select count(a), b from tbl_c group by b
```
it showes the error:
```
Caused by: java.lang.IllegalStateException: Error: no vector named colmn_name in record bach
 at org.apache.spark.sql.execution.datasources.v2.arrow.ArrowUtils$.$anonfun$getDataVectors$1(ArrowUtils.scala:135)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
 at scala.collection.Iterator.foreach(Iterator.scala:941)
 at scala.collection.Iterator.foreach$(Iterator.scala:941)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
 at scala.collection.IterableLike.foreach(IterableLike.scala:74)
 at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
 at org.apache.spark.sql.types.StructType.foreach(StructType.scala:102)
 at scala.collection.TraversableLike.map(TraversableLike.scala:238)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
 at org.apache.spark.sql.types.StructType.map(StructType.scala:102)
 at org.apache.spark.sql.execution.datasources.v2.arrow.ArrowUtils$.getDataVectors(ArrowUtils.scala:132)
 at org.apache.spark.sql.execution.datasources.v2.arrow.ArrowUtils$.loadVectors(ArrowUtils.scala:102)
 at com.intel.oap.spark.sql.execution.datasources.arrow.ArrowFileFormat.$anonfun$buildReaderWithPartitionValues$5(ArrowFileFormat.scala:108)
 at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
 at com.intel.oap.spark.sql.execution.datasources.arrow.ArrowFileFormat$UnsafeItr.next(ArrowFileFormat.scala:135)
 at com.intel.oap.spark.sql.execution.datasources.arrow.ArrowFileFormat$UnsafeItr.next(ArrowFileFormat.scala:117)
 at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.next(FileScanRDD.scala:96)
 at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.next(DataSourceScanExec.scala:506)
 at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.next(DataSourceScanExec.scala:495)
 at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.columnartorow_nextBatch_0$(Unknown Source)
 at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.ag
```

Is the thrift server support still in development?

or we should add some extra config into OAP or spark-default.conf

**Comment by zhouyuan** [comment]
Hi @rollandlee , data source v1 support in 0.9 is limited and maybe buggy, data source v2(spark-shell) should be easier to test with.      The 0.9 release w/ data source v2 should be working on all TPCH queries. 
Note Native SQL project are moving quickly in master branch(targeting for 1.0 release) as of today - new columnar operators and lots of bug fixes. All TPCH/TPC-DS queries are working on current code. The thrift-server support is much better also - you may need to create additional table for Arrow Data Source thought. I can provide more helps in case interested. FYI here's one example on how to create table w/ arrow data source:
https://gist.github.com/zhouyuan/a47f9bfaf5de106cc7627ff5733fae57

thanks, -yuan

**Comment by rollandlee** [comment]
> Hi @rollandlee , data source v1 support in 0.9 is limited and maybe buggy, data source v2(spark-shell) should be easier to test with. The 0.9 release w/ data source v2 should be working on all TPCH queries.
> Note Native SQL project are moving quickly in master branch(targeting for 1.0 release) as of today - new columnar operators and lots of bug fixes. All TPCH/TPC-DS queries are working on current code. The thrift-server support is much better also - you may need to create additional table for Arrow Data Source thought. I can provide more helps in case interested. FYI here's one example on how to create table w/ arrow data source:
> https://gist.github.com/zhouyuan/a47f9bfaf5de106cc7627ff5733fae57
>
> thanks, -yuan

Many Thanks, Let check OAP 1.0

Could you indicate the target release date of OAP 1.0? since it performs much better then any other engine that we can find
