### ISSUE TITLE
[Intel-MLlib] UnsatisfiedLinkError: org.apache.spark.ml.util.OneDAL$.cAddNumericTable

### ISSUE THREAD

**Issue by xwu99** [Intel-bigdata/OAP#1699]
UnsatisfiledLinkError when running a customer workload. The cause is JNI header `native/javah/org_apache_spark_ml_util_OneDAL__.h` is not updated after class code update. 
It's specific for `branch-0.9-spark-3.x`

Caused by: java.lang.UnsatisfiedLinkError: org.apache.spark.ml.util.OneDAL$.cAddNumericTable(JJ)V
        at org.apache.spark.ml.util.OneDAL$.cAddNumericTable(Native Method)
        at org.apache.spark.ml.clustering.KMeansDALImpl.$anonfun$runWithRDDVector$10(KMeansDALImpl.scala:120)
        at scala.runtime.java8.JFunction1$mcVJ$sp.apply(JFunction1$mcVJ$sp.java:23)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)

**Comment by zhixingheyi-tian** [comment]
@xwu99   close this issue?
