### ISSUE TITLE
[OAP-CACHE] Plasma throw exception:get an invalid value- branch 0.8

### ISSUE THREAD

**Issue by offthewall123** [Intel-bigdata/OAP#1918]

**Comment by offthewall123** [comment]
20/11/13 11:56:54 WARN filecache.ExternalCache: plasma object duplicate An object with ID 04763e8f628df7a67ca89848ebe0717400000000 already exists in the plasma store. Will get this object.
20/11/13 11:56:54 ERROR executor.Executor: Exception in task 5.0 in stage 949.0 (TID 304008)
org.apache.arrow.plasma.exceptions.PlasmaGetException: Get returns an invalid value!
at org.apache.arrow.plasma.PlasmaClientJNI.get(Native Method)
at org.apache.arrow.plasma.PlasmaClient.getObjAsByteBuffer(PlasmaClient.java:118)
at org.apache.spark.sql.execution.datasources.oap.filecache.ExternalCache.getEmptyFiber(OapCache.scala:1006)
at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager.getEmptyDataFiberCache(FiberCacheManager.scala:209)
at org.apache.spark.sql.execution.datasources.oap.io.ParquetDataFiberWriter$.emptyDataFiber(ParquetDataFiberReaderWriter.scala:317)
at org.apache.spark.sql.execution.datasources.oap.io.ParquetDataFiberWriter$.dumpToCache(ParquetDataFiberReaderWriter.scala:91)
at org.apache.spark.sql.execution.datasources.oap.io.ParquetFiberDataLoader.loadSingleColumn(ParquetFiberDataLoader.scala:79)
at org.apache.spark.sql.execution.datasources.oap.io.ParquetDataFile.cache(ParquetDataFile.scala:110)
at org.apache.spark.sql.execution.datasources.oap.filecache.OapCache$class.cache(OapCache.scala:377)
at org.apache.spark.sql.execution.datasources.oap.filecache.ExternalCache.cache(OapCache.scala:1112)
at org.apache.spark.sql.execution.datasources.oap.filecache.ExternalCache.get(OapCache.scala:1085)
at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager.get(FiberCacheManager.scala:114)
at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader$$anonfun$readNextRowGroup$3.apply(VectorizedCacheReader.scala:184)
at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader$$anonfun$readNextRowGroup$3.apply(VectorizedCacheReader.scala:176)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader.readNextRowGroup(VectorizedCacheReader.scala:176)
at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader.checkEndOfRowGroup(VectorizedCacheReader.scala:151)
at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader.nextBatch(VectorizedCacheReader.scala:128)
at org.apache.spark.sql.execution.datasources.oap.io.VectorizedCacheReader.nextKeyValue(VectorizedCacheReader.scala:99)
at org.apache.spark.sql.execution.datasources.oap.io.FileRecordReaderIterator.hasNext(DataFile.scala:66)
at org.apache.spark.sql.execution.datasources.oap.io.OapCompletionIterator.hasNext(DataFile.scala:103)
at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:104)
at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:184)
at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:104)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage8.scan_nextBatch_0$(Unknown Source)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage8.agg_doAggregateWithKeys_0$(Unknown Source)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage8.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:187)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
at org.apache.spark.scheduler.Task.run(Task.scala:123)
at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
20/11/13 11:56:55 WARN filecache.ExternalCache: plasma seal object error: Seal() called on an already sealed object
20/11/13 11:56:55 WARN filecache.ExternalCache: plasma seal object error: Seal() called on an already sealed object
20/11/13 11:56:55 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 304152
20/11/13 11:56:55 INFO executor.Executor: Running task 106.0 in stage 952.0 (TID 304152)
20/11/13 11:56:55 INFO datasources.FileScanRDD: Reading File path: hdfs://sr128:9000/tpcds_1t_snappy/catalog_returns/part-00084-37cc75f3-b99e-4868-86fa-4042defe7d68-c000.snappy.parquet, range: 0-72107573, partition values: [empty row]
20/11/13 11:56:55 WARN filecache.ExternalCache: plasma object duplicate An object with ID 330cc1c818db3746c887a542cd76e23900000000 already exists in the plasma store. Will get this object.
20/11/13 11:56:55 WARN filecache.ExternalCache: plasma object duplicate An object with ID d44286cf573d5ba3cefa3fc7c1798d9000000000 already exists in the plasma store. Will get this object.
20/11/13 11:56:55 WARN filecache.ExternalCache: plasma seal object error: Seal() called on an already sealed object
20/11/13 11:56:55 WARN filecache.ExternalCache: plasma seal object error: Seal() called on an already sealed object
20/11/13 11:56:55 WARN filecache.ExternalCache: plasma object duplicate An object with ID 66e3edce4d2368019bad73c8cc5a2deb00000000 already exists in the plasma store. Will get this object.
20/11/13 11:56:55 WARN filecache.ExternalCache: plasma seal object error: Seal() called on an already sealed object
20/11/13 11:56:55 INFO executor.Executor: Finished task 89.0 in stage 949.0 (TID 304030). 6246 bytes result sent to driver
20/11/13 11:56:55 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 304224
20/11/13 11:56:55 INFO executor.Executor: Running task 5.1 in stage 949.0 (TID 304224)
20/11/13 11:56:55 INFO datasources.FileScanRDD: Reading File path: hdfs://sr128:9000/tpcds_1t_snappy/catalog_returns/part-00099-37cc75f3-b99e-4868-86fa-4042defe7d68-c000.snappy.parquet, range: 0-72358834, partition values: [empty row]
20/11/13 11:56:56 INFO executor.Executor: Finished task 89.0 in stage 952.0 (TID 304138). 6928 bytes result sent to driver
20/11/13 11:56:56 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 304225
20/11/13 11:56:56 INFO executor.Executor: Running task 110.0 in stage 952.0 (TID 304225)
20/11/13 11:56:56 INFO datasources.FileScanRDD: Reading File path: hdfs://sr128:9000/tpcds_1t_snappy/catalog_returns/part-00120-37cc75f3-b99e-4868-86fa-4042defe7d68-c000.snappy.parquet, range: 0-72095256, partition values: [empty row]
20/11/13 11:56:56 INFO compat.FilterCompat: Filtering using predicate: and(and(noteq(cr_returned_date_sk, null), noteq(cr_returning_addr_sk, null)), noteq(cr_returning_customer_sk, null))
20/11/13 11:56:56 WARN filecache.ExternalCache: plasma object duplicate An object with ID 58bf6c1760545b8535e1fc5e2d2da80500000000 already exists in the plasma store. Will get this object.
20/11/13 11:56:56 WARN filecache.ExternalCache: plasma seal object error: Seal() called on an already sealed object
20/11/13 11:56:56 INFO executor.Executor: Finished task 106.0 in stage 949.0 (TID 304050). 6289 bytes result sent to driver
20/11/13 11:56:56 INFO compat.FilterCompat: Filtering using predicate: and(noteq(cr_returned_date_sk, null), noteq(cr_returning_addr_sk, null))
20/11/13 11:56:56 INFO executor.Executor: Finished task 106.0 in stage 952.0 (TID 304152). 6928 bytes result sent to driver
20/11/13 11:56:56 WARN filecache.ExternalCache: plasma object duplicate An object with ID 3addd977212ff1e3f568aab2d246439000000000 already exists in the plasma store. Will get this object.
20/11/13 11:56:56 WARN filecache.ExternalCache: plasma seal object error: Seal() called on an already sealed object
20/11/13 11:56:56 INFO executor.Executor: Finished task 110.0 in stage 949.0 (TID 304068). 6289 bytes result sent to driver
20/11/13 11:56:56 INFO executor.Executor: Finished task 110.0 in stage 952.0 (TID 304225). 6842 bytes result sent to driver
