### ISSUE TITLE
ArrayIndexOutOfBoundsException in IndexedScan

### ISSUE THREAD

**Issue by adrian-wang** [Intel-bigdata/OAP#227]
```
create table hive_test (key int, value string);
LOAD DATA LOCAL INPATH '/sql/hive/src/test/resources/data/files/small_kv.txt' OVERWRITE INTO TABLE hive_test;
create table hive_test_spn (key int, value string) using spn;
insert into hive_test_spn select * from hive_test;
create sindex hive_test_spn_idx on hive_test_spn (key, value);
```
I see
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.genericGet(rows.scala:227)
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getAs(rows.scala:35)
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.get(rows.scala:37)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.get(rows.scala:221)
	at org.apache.spark.sql.execution.datasources.spinach.io.DataFile$$anonfun$encodeInterval$2.apply(DataFile.scala:156)
	at org.apache.spark.sql.execution.datasources.spinach.io.DataFile$$anonfun$encodeInterval$2.apply(DataFile.scala:155)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.execution.datasources.spinach.io.DataFile$.encodeInterval(DataFile.scala:155)
	at org.apache.spark.sql.execution.datasources.spinach.index.IndexScanner.encodeIntervalAndSchema(IndexScanner.scala:87)
	at org.apache.spark.sql.execution.datasources.spinach.index.BPlusTreeScanner.initialize(BPlusTreeScanner.scala:42)
	at org.apache.spark.sql.execution.datasources.spinach.io.SpinachDataReader.initialize(SpinachDataReaderWriter.scala:148)
	at org.apache.spark.sql.execution.datasources.spinach.SpinachFileFormat$$anonfun$buildReader$4.apply(SpinachFileFormat.scala:191)
	at org.apache.spark.sql.execution.datasources.spinach.SpinachFileFormat$$anonfun$buildReader$4.apply(SpinachFileFormat.scala:186)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:116)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:91)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by linhong-intel** [comment]
close this and open a new issue #253
