### ISSUE TITLE
ERROR LiveListenerBus: Listener EventLoggingListener threw an exception

### ISSUE THREAD

**Issue by yueawang** [Intel-bigdata/OAP#341]
Found a issue by using recent master code (either 2.0.2 or 2.1.0)

Reproduce step:
Run spark-shell and do any simple query.

Error message:
17/10/11 16:22:46 ERROR LiveListenerBus: Listener EventLoggingListener threw an exception
java.lang.ClassCastException: java.util.Collections$UnmodifiableRandomAccessList cannot be cast to scala.collection.Seq
                at org.apache.spark.util.JsonProtocol$.accumValueToJson(JsonProtocol.scala:316)
                at org.apache.spark.util.JsonProtocol$$anonfun$accumulableInfoToJson$3.apply(JsonProtocol.scala:292)
                at org.apache.spark.util.JsonProtocol$$anonfun$accumulableInfoToJson$3.apply(JsonProtocol.scala:292)
                at scala.Option.map(Option.scala:146)
                at org.apache.spark.util.JsonProtocol$.accumulableInfoToJson(JsonProtocol.scala:292)
                at org.apache.spark.util.JsonProtocol$$anonfun$taskInfoToJson$12.apply(JsonProtocol.scala:285)
                at org.apache.spark.util.JsonProtocol$$anonfun$taskInfoToJson$12.apply(JsonProtocol.scala:285)
                at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
                at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
                at scala.collection.immutable.List.foreach(List.scala:381)
                at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
                at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
                at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
                at scala.collection.AbstractTraversable.map(Traversable.scala:104)
                at org.apache.spark.util.JsonProtocol$.taskInfoToJson(JsonProtocol.scala:285)
                at org.apache.spark.util.JsonProtocol$.taskEndToJson(JsonProtocol.scala:147)
                at org.apache.spark.util.JsonProtocol$.sparkEventToJson(JsonProtocol.scala:76)
                at org.apache.spark.scheduler.EventLoggingListener.logEvent(EventLoggingListener.scala:137)
                at org.apache.spark.scheduler.EventLoggingListener.onTaskEnd(EventLoggingListener.scala:157)
                at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:45)
                at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
                at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
                at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:63)
                at org.apache.spark.scheduler.LiveListenerBus.postToAll(LiveListenerBus.scala:36)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiveListenerBus.scala:94)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
                at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(LiveListenerBus.scala:78)
                at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1252)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1.run(LiveListenerBus.scala:77)
17/10/11 16:22:46 ERROR LiveListenerBus: Listener EventLoggingListener threw an exception
java.lang.ClassCastException: java.util.Collections$UnmodifiableRandomAccessList cannot be cast to scala.collection.Seq
                at org.apache.spark.util.JsonProtocol$.accumValueToJson(JsonProtocol.scala:316)
                at org.apache.spark.util.JsonProtocol$$anonfun$accumulableInfoToJson$5.apply(JsonProtocol.scala:293)
                at org.apache.spark.util.JsonProtocol$$anonfun$accumulableInfoToJson$5.apply(JsonProtocol.scala:293)
                at scala.Option.map(Option.scala:146)
                at org.apache.spark.util.JsonProtocol$.accumulableInfoToJson(JsonProtocol.scala:293)
                at org.apache.spark.util.JsonProtocol$$anonfun$stageInfoToJson$6.apply(JsonProtocol.scala:270)
                at org.apache.spark.util.JsonProtocol$$anonfun$stageInfoToJson$6.apply(JsonProtocol.scala:270)
                at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
                at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
                at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:108)
                at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:108)
                at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
                at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
                at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:108)
                at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
                at scala.collection.AbstractTraversable.map(Traversable.scala:104)
                at org.apache.spark.util.JsonProtocol$.stageInfoToJson(JsonProtocol.scala:270)
                at org.apache.spark.util.JsonProtocol$.stageCompletedToJson(JsonProtocol.scala:118)
                at org.apache.spark.util.JsonProtocol$.sparkEventToJson(JsonProtocol.scala:70)
                at org.apache.spark.scheduler.EventLoggingListener.logEvent(EventLoggingListener.scala:137)
                at org.apache.spark.scheduler.EventLoggingListener.onStageCompleted(EventLoggingListener.scala:163)
                at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:35)
                at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
                at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
                at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:63)
                at org.apache.spark.scheduler.LiveListenerBus.postToAll(LiveListenerBus.scala:36)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiveListenerBus.scala:94)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
                at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(LiveListenerBus.scala:78)
                at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1252)
                at org.apache.spark.scheduler.LiveListenerBus$$anon$1.run(LiveListenerBus.scala:77)

**Comment by linhong-intel** [comment]
If I remember correctly, this is caused by Commit https://github.com/Intel-bigdata/OAP/commit/534d47be0d6e33bb7370e532f8cdaa7593dfedd1
@lee-lei , Can you have a look first when you have time?

**Comment by yueawang** [comment]
I disussed with Lei when I created this issue, it's not a regression caused by his PR.
I am talking this with Daoyuan, see if we can figure out the reason soon.

**Comment by adrian-wang** [comment]
after discussion, we found we are missing a `.asScala` for `JArray`. Let's try if it fixes.
