### ISSUE TITLE
reentrant indexscanner.toArray trigger AssertionError

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#402]
one indexscanner instance call toArray method two times will throw AssertionError as follow:

`java.lang.AssertionError: assertion failed: Block fiber_btree_file:/private/var/folders/cr/mf14vhqn5tbgmqfkxs7jpymh0000gn/T/spark-08f7e8f7-75ac-4e4a-a7a7-5edc9328cdc2/.part-00000-2e3b5833-fc26-4328-a615-4bf4e078ea0c.snappy.15fc4d9eb7b.index1.index_0_0 is not locked for reading
	at scala.Predef$.assert(Predef.scala:170)
	at org.apache.spark.storage.BlockInfoManager.unlock(BlockInfoManager.scala:294)
	at org.apache.spark.storage.BlockManager.releaseLock(BlockManager.scala:654)
	at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager$.releaseLock(FiberCacheManager.scala:104)
	at org.apache.spark.sql.execution.datasources.oap.index.BTreeIndexRecordReader.releaseCache(BTreeIndexRecordReader.scala:198)
	at org.apache.spark.sql.execution.datasources.oap.index.BTreeIndexRecordReader.close(BTreeIndexRecordReader.scala:204)
	at org.apache.spark.sql.execution.datasources.oap.index.BTreeIndexRecordReader.hasNext(BTreeIndexRecordReader.scala:217)
	at org.apache.spark.sql.execution.datasources.oap.index.BPlusTreeScanner.hasNext(BPlusTreeScanner.scala:50)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.sql.execution.datasources.oap.index.IndexScanner.foreach(IndexScanner.scala:40)
`

Is this expected behavior? @linhong-intel

**Comment by adrian-wang** [comment]
since we have move to Guava, is this issue not valid any more?
