### ISSUE TITLE
Test case failed randomly, OapSuite - reading oap file

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#421]
Build link:
https://travis-ci.org/Intel-bigdata/OAP/builds/306592941?utm_source=github_status&utm_medium=notification

**Comment by linhong-intel** [comment]
OapSuite:
- reading oap file *** FAILED ***
  java.lang.NullPointerException: Value at index 0 is null
  at org.apache.spark.sql.Row$class.getAnyValAs(Row.scala:472)
  at org.apache.spark.sql.Row$class.getInt(Row.scala:223)
  at org.apache.spark.sql.catalyst.expressions.GenericRow.getInt(rows.scala:165)
  at org.apache.spark.sql.execution.datasources.oap.OapSuite$$anonfun$9.apply(OapSuite.scala:179)
  at org.apache.spark.sql.execution.datasources.oap.OapSuite$$anonfun$9.apply(OapSuite.scala:179)
  at scala.math.Ordering$$anon$5.compare(Ordering.scala:122)
  at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
  at java.util.TimSort.sort(TimSort.java:234)
  at java.util.Arrays.sort(Arrays.java:1438)
  at scala.collection.SeqLike$class.sorted(SeqLike.scala:648)
  ...
