### ISSUE TITLE
[No reproduce, watching]Get EOFException when testing Bitmap index on range [1, 100] on tpcds 200 dataset

### ISSUE THREAD

**Issue by xuyangit** [Intel-bigdata/OAP#446]
To further test the performance of Bitmap index, I eliminate the range of index attribute to [1, 100].  During test, I get EOFException when using index to deal with the query:
select count(ss_item_sk1) from store_sales where ss_item_sk1 = 20;
The error goes like this:
Caused by: java.io.EOFException: End of file reached before reading fully.
	at org.apache.hadoop.fs.FSInputStream.readFully(FSInputStream.java:80)
	at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:116)
	at org.apache.spark.sql.execution.datasources.oap.filecache.MemoryManager$.putToIndexFiberCache(MemoryManager.scala:172)
	at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner.org$apache$spark$sql$execution$datasources$oap$index$BitMapScanner$$loadBmKeyList(BitMapScanner.scala:109)
	at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner$$anonfun$cacheBitmapAllSegments$2.apply(BitMapScanner.scala:145)
	at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner$$anonfun$cacheBitmapAllSegments$2.apply(BitMapScanner.scala:145)
	at org.apache.spark.sql.execution.datasources.oap.filecache.BitmapFiber.fiber2Data(FiberCacheManager.scala:169)
	at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager$$anon$3.call(FiberCacheManager.scala:72)
	at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager$$anon$3.call(FiberCacheManager.scala:69)
	at org.spark_project.guava.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
	at org.spark_project.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)

Full error log:
[error.txt](https://github.com/Intel-bigdata/OAP/files/1530137/error.txt)

**Comment by yueawang** [comment]
Looks like the index file is corrupted. 
take /user/oap/oaptest/oap-0.3.0/tpcds/tpcds200/oap/store_sales/.part-00035-270c5da8-629a-4cea-9e65-4cf69a31a645.gzip.16025946bc7.store_sales_ss_item_sk1_index.index as a example.
the footer (last 40 bytes) contents are:
xxxx xxxx   xxxx  xxxx  0000 7810 efab abcd
0524 2017 0000 0000 348e 08ab 0000 0000
348e 08ab 0000 0000 348e 08ab 0000 0000

0x20170524abcdefab is written by statistics manager. It looks like the space reserved for stat manager is not big enough, so these extra value were written out to where footer should stands. Will check later.

**Comment by lee-lei** [comment]
Any update about this issue? Thanks.

**Comment by adrian-wang** [comment]
I'll remove the statistic writing part of bitmap index in #453 , then this will not happen.

**Comment by yueawang** [comment]
This can not be reproduced recently, we keep this one open with low priority and see if any special operation turns it on. It will be closed If does not happen in next few rounds of benchmark.
@adrian-wang you can keep the statistics writing which should not be the reason.

**Comment by adrian-wang** [comment]
I have removed corresponding code, so I'll mark this as a dup of #450 , thanks.

**Comment by adrian-wang** [comment]
reopened and cleared from 0.3.0 milestone.
