### ISSUE TITLE
Inaccurate hint information when the off-heap memory is disabled. 

### ISSUE THREAD

**Issue by songzhan01** [Intel-bigdata/OAP#493]
Off-heap memory is disabled by default in spark.

The error is as follows：
org.apache.spark.sql.execution.datasources.OapException: Try to access a freed memory
	at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCache$class.getBaseObj(MemoryManager.scala:58)
	at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCache$class.copyMemory(MemoryManager.scala:88)
	at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCache$class.copyMemoryToLongs(MemoryManager.scala:91)
	at org.apache.spark.sql.execution.datasources.oap.filecache.DataFiberCache.copyMemoryToLongs(MemoryManager.scala:111)
	at org.apache.spark.sql.execution.datasources.oap.ColumnValues.<init>(ColumnValues.scala:39)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataFile$$anonfun$3$$anonfun$5.apply(OapDataFile.scala:124)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataFile$$anonfun$3$$anonfun$5.apply(OapDataFile.scala:123)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataFile$$anonfun$3.apply(OapDataFile.scala:123)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataFile$$anonfun$3.apply(OapDataFile.scala:119)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:32)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:166)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.execute(FileFormatWriter.scala:246)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:193)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:191)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1341)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:196)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by songzhan01** [comment]
PR#491 contains a similar change with this issue， close it.
