### ISSUE TITLE
Use BitMap Index throw EOFException

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#604]
There are 2 files in data path and when I query as follow:
`val df = spark.sqlContext.read.format("parquet").load("file:///home/work/pdata/")
  df.registerTempTable("fc_ad_wise")
  spark.sql("CREATE OINDEX planid_index on fc_ad_wise (planid) USING BITMAP").collect
  spark.sql("select  userid, winfoid FROM fc_ad_wise WHERE planid='74676823'").collect
`
it will throw EOFException and stack as follow:
`
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 4, localhost, executor driver): java.util.concurrent.ExecutionException: java.io.EOFException: End of file reached before reading fully.
        at org.spark_project.guava.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
        at org.spark_project.guava.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:293)
        at org.spark_project.guava.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at org.spark_project.guava.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:135)
        at org.spark_project.guava.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2410)
        at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2380)
        at org.spark_project.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
        at org.spark_project.guava.cache.LocalCache$Segment.get(LocalCache.java:2257)
        at org.spark_project.guava.cache.LocalCache.get(LocalCache.java:4000)
        at org.spark_project.guava.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
        at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache.get(OapCache.scala:132)
        at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager$.get(FiberCacheManager.scala:121)
        at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner.analyzeStatistics(BitMapScanner.scala:130)
        at org.apache.spark.sql.execution.datasources.oap.index.IndexScanner.tryAnalyzeStatistics(IndexScanner.scala:157)
        at org.apache.spark.sql.execution.datasources.oap.index.IndexScanner.readBehavior(IndexScanner.scala:134)
        at org.apache.spark.sql.execution.datasources.oap.index.IndexScanner.readBehavior(IndexScanner.scala:82)
        at org.apache.spark.sql.execution.datasources.oap.index.IndexScanners$$anonfun$4.apply(IndexScanner.scala:332)
        at org.apache.spark.sql.execution.datasources.oap.index.IndexScanners$$anonfun$4.apply(IndexScanner.scala:332)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.execution.datasources.oap.index.IndexScanners.indexIsAvailable(IndexScanner.scala:332)
        at org.apache.spark.sql.execution.datasources.oap.io.OapDataReader.initialize(OapDataReaderWriter.scala:204)
        at org.apache.spark.sql.execution.datasources.oap.OapFileFormat$$anonfun$buildReaderWithPartitionValues$5.apply(OapFileFormat.scala:310)
        at org.apache.spark.sql.execution.datasources.oap.OapFileFormat$$anonfun$buildReaderWithPartitionValues$5.apply(OapFileFormat.scala:283)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:150)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:166)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:231)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:225)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: End of file reached before reading fully.
        at org.apache.hadoop.fs.FSInputStream.readFully(FSInputStream.java:80)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:116)
        at org.apache.spark.sql.execution.datasources.oap.filecache.MemoryManager$.putToIndexFiberCache(MemoryManager.scala:237)
        at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner.org$apache$spark$sql$execution$datasources$oap$index$BitMapScanner$$loadBmStatsContent(BitMapScanner.scala:95)
        at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner$$anonfun$1.apply(BitMapScanner.scala:128)
        at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner$$anonfun$1.apply(BitMapScanner.scala:128)
        at org.apache.spark.sql.execution.datasources.oap.filecache.BitmapFiber.fiber2Data(FiberCacheManager.scala:263)
        at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache$$anon$3.call(OapCache.scala:112)
        at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache$$anon$3.call(OapCache.scala:109)
        at org.spark_project.guava.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
        at org.spark_project.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
        at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
        ... 42 more
`

and when I set `spark.sql.oap.oindex.statistics.policy = false`, the stack will like

`
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 4, localhost, executor driver): java.util.concurrent.ExecutionException: java.io.EOFException: End of file reached before reading fully.
        at org.spark_project.guava.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
        at org.spark_project.guava.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:293)
        at org.spark_project.guava.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at org.spark_project.guava.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:135)
        at org.spark_project.guava.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2410)
        at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2380)
        at org.spark_project.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
        at org.spark_project.guava.cache.LocalCache$Segment.get(LocalCache.java:2257)
        at org.spark_project.guava.cache.LocalCache.get(LocalCache.java:4000)
        at org.spark_project.guava.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
        at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache.get(OapCache.scala:132)
        at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager$.get(FiberCacheManager.scala:121)
        at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner.cacheBitmapAllSegments(BitMapScanner.scala:230)
        at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner.initialize(BitMapScanner.scala:348)
        at org.apache.spark.sql.execution.datasources.oap.index.IndexScanners.initialize(IndexScanner.scala:351)
        at org.apache.spark.sql.execution.datasources.oap.io.OapDataReader.getRowIds$1(OapDataReaderWriter.scala:206)
        at org.apache.spark.sql.execution.datasources.oap.io.OapDataReader.initialize(OapDataReaderWriter.scala:227)
        at org.apache.spark.sql.execution.datasources.oap.OapFileFormat$$anonfun$buildReaderWithPartitionValues$5.apply(OapFileFormat.scala:310)
        at org.apache.spark.sql.execution.datasources.oap.OapFileFormat$$anonfun$buildReaderWithPartitionValues$5.apply(OapFileFormat.scala:283)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:150)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:166)
        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:231)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:225)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: End of file reached before reading fully.
        at org.apache.hadoop.fs.FSInputStream.readFully(FSInputStream.java:80)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:116)
        at org.apache.spark.sql.execution.datasources.oap.filecache.MemoryManager$.putToIndexFiberCache(MemoryManager.scala:237)
        at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner.org$apache$spark$sql$execution$datasources$oap$index$BitMapScanner$$loadBmOffsetList(BitMapScanner.scala:187)
        at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner$$anonfun$cacheBitmapAllSegments$3.apply(BitMapScanner.scala:229)
        at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner$$anonfun$cacheBitmapAllSegments$3.apply(BitMapScanner.scala:229)
        at org.apache.spark.sql.execution.datasources.oap.filecache.BitmapFiber.fiber2Data(FiberCacheManager.scala:263)
        at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache$$anon$3.call(OapCache.scala:112)
        at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache$$anon$3.call(OapCache.scala:109)
        at org.spark_project.guava.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
        at org.spark_project.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
        at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
        ... 33 more
`
And if planid_index is BTREE Index, query will success.

**Comment by LuciferYang** [comment]
@carsonwang  @yueawang @adrian-wang 
if `spark.sql.oap.oindex.statistics.policy = true`,` BitMapScanner.analyzeStatistics(130)` will throw `EOFException`, and if `spark.sql.oap.oindex.statistics.policy = false` `BitMapScanner.cacheBitmapAllSegments(230)` will throw `EOFException`

**Comment by LuciferYang** [comment]
Use Oap V0.3

**Comment by yueawang** [comment]
Could you please list last 20 Int of the index file?

**Comment by lee-lei** [comment]
Also, would you please help check if the OapV0.3 you are using is from the branch upstream/branch-0.3? Thanks.

**Comment by LuciferYang** [comment]
@yueawang index data no problem, if data path has only 1 file, query will success.

**Comment by LuciferYang** [comment]
@lee-lei master & branch-0.3 have same problem.

**Comment by LuciferYang** [comment]
@yueawang @lee-lei, had discuss with @adrian-wang, maybe BitMapScanner has problem, one execution slot will use same BitMapScanner instance and it should'nt Stateful.

**Comment by LuciferYang** [comment]
Thx @adrian-wang fix this bug~
