### ISSUE TITLE
Saving data frame as OAP table fails

### ISSUE THREAD

**Issue by mshtelma** [Intel-bigdata/OAP#645]
Hi Team, 

I have tried saving my data frame as OAP Table in Hive. 
I have used Spark 2.1.2 and OAP 0.4-SNAPSHOT
As the result the following exception was thrown: 

scala> myDF.write.format("oap").mode("overwrite").saveAsTable("MyTBL")
18/03/31 10:13:38 WARN Utils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.debug.maxToStringFields' in SparkEnv.conf.
[Stage 1:>                                                        (0 + 48) / 61]18/03/31 10:13:39 ERROR Executor: Exception in task 26.0 in stage 1.0 (TID 27)
scala.NotImplementedError: not implemented type for fiber builder
	at org.apache.spark.sql.execution.datasources.oap.filecache.DataFiberBuilder$.apply(FiberBuilder.scala:324)
	at org.apache.spark.sql.execution.datasources.oap.filecache.DataFiberBuilder$$anonfun$initializeFromSchema$1.apply(FiberBuilder.scala:332)
	at org.apache.spark.sql.execution.datasources.oap.filecache.DataFiberBuilder$$anonfun$initializeFromSchema$1.apply(FiberBuilder.scala:331)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.sql.execution.datasources.oap.filecache.DataFiberBuilder$.initializeFromSchema(FiberBuilder.scala:331)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataWriter.<init>(OapDataReaderWriter.scala:63)
	at org.apache.spark.sql.execution.datasources.oap.OapOutputWriter.<init>(OapFileFormat.scala:515)
	at org.apache.spark.sql.execution.datasources.oap.OapOutputWriterFactory.newInstance(OapFileFormat.scala:408)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.<init>(FileFormatWriter.scala:234)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:182)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by linhong-intel** [comment]
@mshtelma 
Oap only supports basic data type now. Seems you are using some data type not be supported yet.
Can you paste your table schema here to help use check?

**Comment by mshtelma** [comment]
@linhong-intel 
Here are the data types that were used in the tables : 
StringType, IntegerType, TimestampType, DecimalType(38,10), DoubleType, DecimalType(38,0), DateType
Maybe it is the decimal type, there are always a lot of problem with decimals in spark..

**Comment by chenghao-intel** [comment]
thank you @mshtelma . we will add decimal support in 0.4 release.

**Comment by mshtelma** [comment]
@chenghao-intel Thank you too! 
btw, another question, when are going to start supporting spark  2.3 ?

**Comment by linhong-intel** [comment]
duplicate to #676. close this.
