### ISSUE TITLE
Executor lost cause by FiberCacheManager.status method

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#702]
FiberCacheManager.status assume  `dataFile` is InstanceOf `OapDataFile`, but it may be a `ParquetDataFile` instance, when dataFile is a `ParquetDataFile` instance, there will throw `ClassCastException`,  heartbeat will report failure and executor will lost cause by heartbeat timeout.

**Comment by LuciferYang** [comment]
Error stack as follow:

[driver-heartbeater] ERROR Utils: Uncaught exception in thread driver-heartbeater
java.lang.ClassCastException: org.apache.spark.sql.execution.datasources.oap.io.ParquetDataFileHandle cannot be cast to org.apache.spark.sql.execution.datasources.oap.io.OapDataFileHandle
        at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager$$anonfun$6.apply(FiberCacheManager.scala:162)
        at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager$$anonfun$6.apply(FiberCacheManager.scala:160)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager$.status(FiberCacheManager.scala:160)
        at org.apache.spark.sql.execution.datasources.oap.filecache.OapFiberCacheHeartBeatMessager.status(FiberCacheManager.scala:39)
        at org.apache.spark.executor.Executor$$anonfun$12.apply(Executor.scala:549)
        at org.apache.spark.executor.Executor$$anonfun$12.apply(Executor.scala:549)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:549)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply$mcV$sp(Executor.scala:582)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:582)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:582)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1951)
        at org.apache.spark.executor.Executor$$anon$1.run(Executor.scala:582)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
