### ISSUE TITLE
NullPointerException is thrown when test bitmap using master.

### ISSUE THREAD

**Issue by songzhan01** [Intel-bigdata/OAP#781]
211630 18/06/06 12:14:12 ERROR executor.Executor: Exception in task 0.0 in stage 115.0 (TID 215168)
211631 org.spark_project.guava.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
211632         at org.spark_project.guava.cache.LocalCache$Segment.get(LocalCache.java:2263)
211633         at org.spark_project.guava.cache.LocalCache.get(LocalCache.java:4000)
211634         at org.spark_project.guava.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
211635         at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache.get(OapCache.scala:159)
211636         at org.apache.spark.sql.execution.datasources.oap.filecache.FiberCacheManager.get(FiberCacheManager.scala:115)
211637         at org.apache.spark.sql.execution.datasources.oap.index.BitmapReader.getFooterCache(BitmapReader.scala:70)
211638         at org.apache.spark.sql.execution.datasources.oap.index.BitmapReader.analyzeStatistics(BitmapReader.scala:186)
211639         at org.apache.spark.sql.execution.datasources.oap.index.BitMapScanner.analyzeStatistics(BitMapScanner.scala:76)
211640         at org.apache.spark.sql.execution.datasources.oap.index.IndexScanner.tryAnalyzeStatistics(IndexScanner.scala:163)
211641         at org.apache.spark.sql.execution.datasources.oap.index.IndexScanner.readBehavior(IndexScanner.scala:140)
211642         at org.apache.spark.sql.execution.datasources.oap.index.IndexScanner.readBehavior(IndexScanner.scala:85)
211643         at org.apache.spark.sql.execution.datasources.oap.index.IndexScanners$$anonfun$4.apply(IndexScanner.scala:350)
211644         at org.apache.spark.sql.execution.datasources.oap.index.IndexScanners$$anonfun$4.apply(IndexScanner.scala:350)
211645         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
211646         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
211647         at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
211648         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
211649         at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
211650         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
211651         at org.apache.spark.sql.execution.datasources.oap.index.IndexScanners.indexIsAvailable(IndexScanner.scala:350)
211652         at org.apache.spark.sql.execution.datasources.oap.io.OapDataReader.initialize(OapDataReaderWriter.scala:232)
211653         at org.apache.spark.sql.execution.datasources.oap.OapFileFormat$$anonfun$buildReaderWithPartitionValues$5.apply(OapFileFormat.scala:291)
211654         at org.apache.spark.sql.execution.datasources.oap.OapFileFormat$$anonfun$buildReaderWithPartitionValues$5.apply(OapFileFormat.scala:256)
211655         at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:168)
211656         at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:109)
211657         at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
211658         at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
211659         at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:380)
211660         at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:231)
211661         at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:225)
211662         at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
211663         at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
211664         at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
211665         at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
211666         at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
211667         at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
211668         at org.apache.spark.scheduler.Task.run(Task.scala:99)
211669         at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
211670         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
211671         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
211672         at java.lang.Thread.run(Thread.java:745)
211673 Caused by: java.lang.NullPointerException
211674         at org.apache.hadoop.fs.BufferedFSInputStream.readFully(BufferedFSInputStream.java:113)
211675         at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:116)
211676         at org.apache.spark.sql.execution.datasources.oap.filecache.MemoryManager.toIndexFiberCache(MemoryManager.scala:86)
211677         at org.apache.spark.sql.execution.datasources.oap.index.impl.IndexFileReaderImpl.readFiberCache(IndexFileReaderImpl.scala:37)
211678         at org.apache.spark.sql.execution.datasources.oap.index.BitmapReader$$anonfun$1.apply(BitmapReader.scala:68)
211679         at org.apache.spark.sql.execution.datasources.oap.index.BitmapReader$$anonfun$1.apply(BitmapReader.scala:68)
211680         at org.apache.spark.sql.execution.datasources.oap.filecache.BitmapFiber.cache(Fiber.scala:74)
211681         at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache$$anon$3.call(OapCache.scala:138)
211682         at org.apache.spark.sql.execution.datasources.oap.filecache.GuavaOapCache$$anon$3.call(OapCache.scala:135)
211683         at org.spark_project.guava.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
211684         at org.spark_project.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)

**Comment by linhong-intel** [comment]
@lee-lei please prioritize this issue.

**Comment by lee-lei** [comment]
Thanks. It's my fault. The file reader close should be after analyzeStatistics.

**Comment by lee-lei** [comment]
I will upload the fix soon. Thanks.

**Comment by lee-lei** [comment]
The PR#783 will fix this issue. Thanks.
