### ISSUE TITLE
Cannot instantiate class org.apache.spark.sql.execution.datasources.oap.io.OapDataFile

### ISSUE THREAD

**Issue by JkSelf** [Intel-bigdata/OAP#791]
Job aborted due to stage failure: Task 31 in stage 0.0 failed 4 times, most recent failure: Lost task 31.3 in stage 0.0 (TID 118, sr532, executor 1): org.apache.spark.sql.execution.datasources.OapException: Cannot instantiate class org.apache.spark.sql.execution.datasources.oap.io.OapDataFile
	at org.apache.spark.sql.execution.datasources.oap.io.DataFile$.apply(DataFile.scala:80)
	at org.apache.spark.sql.execution.datasources.oap.OapFileFormat$$anonfun$buildReaderWithPartitionValues$5.isSkippedByFile$1(OapFileFormat.scala:261)
	at org.apache.spark.sql.execution.datasources.oap.OapFileFormat$$anonfun$buildReaderWithPartitionValues$5.apply(OapFileFormat.scala:275)
	at org.apache.spark.sql.execution.datasources.oap.OapFileFormat$$anonfun$buildReaderWithPartitionValues$5.apply(OapFileFormat.scala:255)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:150)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:30)
	at org.spark_project.guava.collect.Ordering.leastOf(Ordering.java:628)
	at org.apache.spark.util.collection.Utils$.takeOrdered(Utils.scala:37)
	at org.apache.spark.sql.execution.TakeOrderedAndProjectExec$$anonfun$5.apply(limit.scala:148)
	at org.apache.spark.sql.execution.TakeOrderedAndProjectExec$$anonfun$5.apply(limit.scala:147)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor50.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.sql.execution.datasources.oap.io.DataFile$$anonfun$2.apply(DataFile.scala:77)
	at org.apache.spark.sql.execution.datasources.oap.io.DataFile$$anonfun$2.apply(DataFile.scala:77)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.sql.execution.datasources.oap.io.DataFile$.apply(DataFile.scala:77)
	... 29 more
Caused by: java.util.concurrent.ExecutionException: java.io.EOFException
	at org.spark_project.guava.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
	at org.spark_project.guava.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:293)
	at org.spark_project.guava.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at org.spark_project.guava.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:135)
	at org.spark_project.guava.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2410)
	at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2380)
	at org.spark_project.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at org.spark_project.guava.cache.LocalCache$Segment.get(LocalCache.java:2257)
	at org.spark_project.guava.cache.LocalCache.get(LocalCache.java:4000)
	at org.spark_project.guava.cache.LocalCache.getOrLoad(LocalCache.java:4004)
	at org.spark_project.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
	at org.apache.spark.sql.execution.datasources.oap.filecache.DataFileMetaCacheManager.get(FiberCacheManager.scala:214)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataFile.<init>(OapDataFile.scala:45)
	... 36 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.apache.spark.sql.execution.datasources.oap.io.ColumnStatistics$.apply(OapDataFileMeta.scala:175)
	at org.apache.spark.sql.execution.datasources.oap.io.RowGroupMeta$$anonfun$read$3.apply$mcVI$sp(OapDataFileMeta.scala:122)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at org.apache.spark.sql.execution.datasources.oap.io.RowGroupMeta.read(OapDataFileMeta.scala:122)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataFileMeta$$anonfun$read$5.apply$mcVI$sp(OapDataFileMeta.scala:341)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataFileMeta.read(OapDataFileMeta.scala:340)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataFile.getDataFileMeta(OapDataFile.scala:214)
	at org.apache.spark.sql.execution.datasources.oap.io.OapDataFile.getDataFileMeta(OapDataFile.scala:37)
	at org.apache.spark.sql.execution.datasources.oap.filecache.DataFileMetaCacheManager$$anon$2.load(FiberCacheManager.scala:207)
	at org.apache.spark.sql.execution.datasources.oap.filecache.DataFileMetaCacheManager$$anon$2.load(FiberCacheManager.scala:203)
	at org.spark_project.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	... 43 more

**Comment by gczsjdy** [comment]
OAP file format(not Parquet) data file generated before #707 can't be used by later reader.
We consider the backward compatibility of OAP file format(this project introduced) from #784 ,
and the data file layout defined in #707 is the 1st version we support.

So I will close this.
