### ISSUE TITLE
RUN error.

### ISSUE THREAD

**Issue by yunfan123** [Intel-bigdata/OAP#822]
It seems oap overwrite the DataSourceAnalysis class.It is conflict with spark DataSourceAnalysis class.
java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.DataSourceAnalysis.<init>(Lorg/apache/spark/sql/internal/SQLConf;)V
  at org.apache.spark.sql.hive.HiveSessionState$$anon$1.<init>(HiveSessionState.scala:66)
  at org.apache.spark.sql.hive.HiveSessionState.analyzer$lzycompute(HiveSessionState.scala:60)
  at org.apache.spark.sql.hive.HiveSessionState.analyzer(HiveSessionState.scala:59)
  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:69)
  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:67)
  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:50)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:63)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:592)
  ... 48 elided

**Comment by yunfan123** [comment]
It becauses of only support spark with tag v2.1.0. Not the spark branch 2.1.
