### ISSUE TITLE
TestSuite extends SharedOapContext can't run Independent

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#877]
Independent run a test suite exetnds SharedOapContext(like `FilterSuite`)  in ide will errors as following stack, but maven test no problems.
```
Exception encountered when invoking run on a nested suite - None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at org.apache.spark.sql.hive.thriftserver.OapEnv$.initWithoutCreatingOapSession(OapEnv.scala:82)
	at org.apache.spark.sql.oap.OapDriverRuntime.<init>(OapRuntime.scala:57)
	at org.apache.spark.sql.oap.OapRuntime$.init(OapRuntime.scala:155)
	at org.apache.spark.sql.oap.OapRuntime$.init(OapRuntime.scala:145)
	at org.apache.spark.sql.oap.OapRuntime$.getOrCreate(OapRuntime.scala:138)
	at org.apache.spark.sql.test.oap.SharedOapContext$class.createSparkSession(SharedOapContext.scala:35)
	at org.apache.spark.sql.execution.datasources.oap.FilterSuite.createSparkSession(FilterSuite.scala:34)
	at org.apache.spark.sql.test.SharedSQLContext$class.beforeAll(SharedSQLContext.scala:62)
	at org.apache.spark.sql.execution.datasources.oap.FilterSuite.org$apache$spark$sql$test$oap$SharedOapContextBase$$super$beforeAll(FilterSuite.scala:34)
	at org.apache.spark.sql.test.oap.SharedOapContextBase$class.beforeAll(SharedOapContext.scala:60)
	at org.apache.spark.sql.execution.datasources.oap.FilterSuite.beforeAll(FilterSuite.scala:42)
	at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
	at org.apache.spark.SparkFunSuite.beforeAll(SparkFunSuite.scala:31)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
	at org.apache.spark.SparkFunSuite.run(SparkFunSuite.scala:31)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

**Comment by LuciferYang** [comment]
```
git reset --hard df81fad495b4208af7e1b66d2f2e090fa7c932eeczsjdy 
HEAD is now at df81fad495 Add sparkSession to OapRuntime for easy control (#834)
```
still has this error  

```
git reset --hard ffd4bcfccbfae874bfea837cefe37f70c88659d5
HEAD is now at ffd4bcfccb Abstract MemoryManager to support more memory type (#863)
```
will ok 

@gczsjdy help to check together？

**Comment by gczsjdy** [comment]
In unit tests, it is not supposed to go into that function: `initWithoutCreatingOapSession`
However, in Intellij unit tests, Utils.isTesting is false...

**Comment by gczsjdy** [comment]
Try to set SPARK_TESTING in Environmental Variables , refer to:https://stackoverflow.com/questions/13748784/setting-up-and-using-environmental-variables-in-intellij-idea

**Comment by LuciferYang** [comment]
```
trait SharedOapContext extends SharedOapContextBase {

  System.setProperty("spark.testing", "true") // add this line will test pass

  protected override def createSparkSession: TestSparkSession = {
    val testSession = new TestOapSession(oapSparkConf)
    OapRuntime.getOrCreate.asInstanceOf[OapDriverRuntime].setTestSession(testSession)
    testSession
  }
}
```
add this line can workaround,

**Comment by LuciferYang** [comment]
#994 fix this
