### ISSUE TITLE
One exception happened when generating TPCDS data based on OAP for Spark 2.1

### ISSUE THREAD

**Issue by lee-lei** [Intel-bigdata/OAP#894]
Based on the latest OAP master for Spark 2.1, when generating TPCDS data using genData API based on spark-shell, below exception happened:

scala> import com.databricks.spark.sql.perf.tpcds.Tables
import com.databricks.spark.sql.perf.tpcds.Tables

scala> val tables = new Tables(spark.sqlContext, tools_path, scale)
tables: com.databricks.spark.sql.perf.tpcds.Tables = com.databricks.spark.sql.perf.tpcds.Tables@7a285418

scala> tables.genData(data_path, format, true, false, true, false, false, "call_center", 1)
Generating table call_center in database to hdfs://sr530:9000/tpcds_orc_debug/tpcds_10_orc_snappy_2_1/call_center with save mode Overwrite.
18/10/11 11:34:51 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, sr554, executor 2): java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apache.spark.rdd.MapPartitionsRDD
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2233)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1405)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2283)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2201)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2277)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2201)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:426)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2168)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2277)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2201)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2277)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2201)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:426)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2168)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2277)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2201)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2277)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2201)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:426)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2168)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2277)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2201)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2277)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2201)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:426)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:80)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

18/10/11 11:34:52 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
18/10/11 11:34:52 WARN Signaling: Cancelling all active jobs, this can take a while. Press Ctrl+C again to exit now.
18/10/11 11:34:52 ERROR FileFormatWriter: Aborting job null.

**Comment by lee-lei** [comment]
The above exception happened for all of the three formats(oap, parquet, and orc).

**Comment by lee-lei** [comment]
Actually this issue is a known issue. The similar issue was reported in Spark community as well. Take below link as an example.
https://issues.apache.org/jira/browse/SPARK-19938

The exception

**Comment by lee-lei** [comment]
Actually this issue is a known issue. The similar issue was reported in Spark community as well. Take below link as an example.
https://issues.apache.org/jira/browse/SPARK-19938

**Comment by lee-lei** [comment]
After changing from yarn to local mode, the tpcds data can be generated successfully. Thus this known issue should be related to the environment setting. It's not related to orc itself. Thanks.
