### ISSUE TITLE
When run with spark 2.1 we got below error

### ISSUE THREAD

**Issue by caneGuy** [Intel-bigdata/OAP#896]
`Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.rpc.RpcEnv$.create(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILorg/apache/spark/SparkConf;Lorg/apache/spark/SecurityManager;Z)Lorg/apache/spark/rpc/RpcEnv;
        at org.apache.spark.SparkEnv$.create(SparkEnv.scala:247)
        at org.apache.spark.SparkEnv$.createExecutorEnv(SparkEnv.scala:202)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:234)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:67)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:66)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1885)
        at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:66)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:199)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:302)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)`

**Comment by LuciferYang** [comment]
@caneGuy which specific version of spark you used? I can't find the create method with the signature like
```
org.apache.spark.rpc.RpcEnv$.create(
Ljava/lang/String;
Ljava/lang/String;
Ljava/lang/String;
ILorg/apache/spark/SparkConf;Lorg/apache/spark/SecurityManager;Z)
Lorg/apache/spark/rpc/RpcEnv; 
```

**Comment by caneGuy** [comment]
i use spark 2.1 @LuciferYang

**Comment by caneGuy** [comment]
i have found the error. Since we modify some code in our inner branch.

**Comment by LuciferYang** [comment]
Thanks for your feedback ~ Oap will work hard to avoid introduce code from spark  ~
