### ISSUE TITLE
One exception happened when running OAP’DailyTest in Spark 2.2

### ISSUE THREAD

**Issue by zhixingheyi-tian** [Intel-bigdata/OAP#904]
Now，for the release of OAP 0.5，OAP’DailyTest is running every day.One exception happened when running OAP’DailyTest in Spark 2.2
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/server/handler/ContextHandler
	at org.apache.spark.ui.SparkUI.initialize(SparkUI.scala:76)
	at org.apache.spark.ui.SparkUI.<init>(SparkUI.scala:84)
	at org.apache.spark.ui.SparkUI$.create(SparkUI.scala:221)
	at org.apache.spark.ui.SparkUI$.createLiveUI(SparkUI.scala:163)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:452)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2509)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:909)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:901)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:901
```

But,there is  no such exception in Spark 2.3.
 when
git reset --hard 11aa4827f6fc9bee8ee509b0865bce04c3ffd333(config parquet version in diff profile (#884))
The  exception  is missing.
when
git reset --hard cafea8f7de98266d765f70fdc74bbdbe7eb0ad71(Add classifier tag to default-jar build process#868 (#880))
The  exception occurs.

This error may be due to #880 .
Please pay some attention,  @LuciferYang 
Thanks

**Comment by LuciferYang** [comment]
we should use `org.spark_project.jetty` package code , not `org.eclipse.jetty.server` because sparkrepackage jetty code to spark-core but not include jetty*.jar

**Comment by LuciferYang** [comment]
@zhixingheyi-tian 2.1 no this problem?
