### ISSUE TITLE
[OAP-0.5]All Parquet Query can't run with Spark-2.1.1

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#935]
#843 Introduce UTF8String.java from spark-2.3, this class change signature of toXXX method(like toInt or toLong) between spark-2.1.0 to spark-2.3.0

- spark-2.1.0 no these methods

- after SPARK-19178(spark-2.1.1)  add `UTF8String.toXXX` methods and signature as following:
`int toInt() ` there is no args of these methods

- after SPARK-19843 (spark-2.2.0) `UTF8String.toXXX` methods changed signature as following:
`boolean toInt(IntWrapper intWrapper) `

Run all parquet query with oap 0.5 and spark-2.1.1 will trigger `java.lang.NoSuchMethodError: org.apache.spark.unsafe.types.UTF8String.toInt()I` problem,  there is no problem before #843.

Spark-2.1.2 & Spark-2.1.3 has same signature of `UTF8String.toXXX` method, so these versions should also have problems.

I don't know if there will be any other problems we run spark-2.1.x  + oap with `UTF8String.java` from spark-2.3, but I think we should fix this problems because oap 0.5 may the last version we support spark-2.1.x

**Comment by LuciferYang** [comment]
```
ava.lang.NoSuchMethodError: org.apache.spark.unsafe.typ
es.UTF8String.toInt()I
        at org.apache.spark.sql.catalyst.expressions.Cast$$anonfun$castToInt$1$$anonfun$apply$36.apply(Cast.scala:266)
        at org.apache.spark.sql.catalyst.expressions.Cast$$anonfun$castToInt$1$$anonfun$apply$36.apply(Cast.scala:266)
        at org.apache.spark.sql.catalyst.expressions.Cast.org$apache$spark$sql$catalyst$expressions$Cast$$buildCast(Cast.scala:139)
        at org.apache.spark.sql.catalyst.expressions.Cast$$anonfun$castToInt$1.apply(Cast.scala:266)
        at org.apache.spark.sql.catalyst.expressions.Cast.nullSafeEval(Cast.scala:449)
        at org.apache.spark.sql.catalyst.expressions.UnaryExpression.eval(Expression.scala:325)
        at org.apache.spark.sql.catalyst.catalog.CatalogTablePartition$$anonfun$toRow$1.apply(interface.scala:114)
        at org.apache.spark.sql.catalyst.catalog.CatalogTablePartition$$anonfun$toRow$1.apply(interface.scala:113)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at org.apache.spark.sql.types.StructType.foreach(StructType.scala:96)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at org.apache.spark.sql.types.StructType.map(StructType.scala:96)
        at org.apache.spark.sql.catalyst.catalog.CatalogTablePartition.toRow(interface.scala:113)
        at org.apache.spark.sql.execution.datasources.CatalogFileIndex$$anonfun$2.apply(CatalogFileIndex.scala:75)
        at org.apache.spark.sql.execution.datasources.CatalogFileIndex$$anonfun$2.apply(CatalogFileIndex.scala:71)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.execution.datasources.CatalogFileIndex.filterPartitions(CatalogFileIndex.scala:71)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog$$anonfun$5$$anonfun$6.apply(HiveMetastoreCatalog.scala:242)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog$$anonfun$5$$anonfun$6.apply(HiveMetastoreCatalog.scala:234)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog$$anonfun$5.apply(HiveMetastoreCatalog.scala:234)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog$$anonfun$5.apply(HiveMetastoreCatalog.scala:224)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog.withTableCreationLock(HiveMetastoreCatalog.scala:63)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog.org$apache$spark$sql$hive$HiveMetastoreCatalog$$convertToLogicalRelation(HiveMetastoreCatalog.scala:224)
at org.apache.spark.sql.hive.HiveMetastoreCatalog$ParquetConversions$.org$apache$spark$sql$hive$HiveMetastoreCatalog$ParquetConversions$$convertToParquetRelation(HiveMeta
storeCatalog.scala:315)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog$ParquetConversions$$anonfun$apply$1.applyOrElse(HiveMetastoreCatalog.scala:332)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog$ParquetConversions$$anonfun$apply$1.applyOrElse(HiveMetastoreCatalog.scala:323)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:310)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:310)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:309)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:307)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:307)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:331)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:188)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:329)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:307)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:307)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:307)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:331)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:188)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:329)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:307)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog$ParquetConversions$.apply(HiveMetastoreCatalog.scala:323)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog$ParquetConversions$.apply(HiveMetastoreCatalog.scala:302)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
        at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:62)
        at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:48)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:63)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:592)
```

**Comment by LuciferYang** [comment]
In oap project, update spark version to spark-2.1.1 of spark-2.1 profile, then run the test suite as following:
```
test("CAST string to int") {
    val data: Seq[(Int, String)] = (1 to 300).map { i => (i, s"$i") }
    data.toDF("key", "value").createOrReplaceTempView("t")
    sql("insert overwrite table parquet_test select * from t")

    withSQLConf(OapConf.OAP_PARQUET_DATA_CACHE_ENABLED.key -> "true") {
      val df = sql("SELECT CAST(b as Int) FROM parquet_test WHERE b = 'this is test 1'").collect()
    }
  }
```
can reproduce the problem, `CAST(b as Int) ` part trigger UTF8String call toInt method, with 2.1.1 will throw Exception as follow:
```
org.codehaus.commons.compiler.CompileException: File 'generated.java', Line 92, Column 34: No applicable constructor/method found for zero actual parameters; candidates are: "public boolean org.apache.spark.unsafe.types.UTF8String.toInt(org.apache.spark.unsafe.types.UTF8String$IntWrapper)"
```

**Comment by LuciferYang** [comment]
```
/* 001 */ public Object generate(Object[] references) {
/* 002 */   return new GeneratedIterator(references);
/* 003 */ }
/* 004 */
/* 005 */ final class GeneratedIterator extends org.apache.spark.sql.execution.BufferedRowIterator {
/* 006 */   private Object[] references;
/* 007 */   private scala.collection.Iterator[] inputs;
/* 008 */   private scala.collection.Iterator scan_input;
/* 009 */   private org.apache.spark.sql.execution.metric.SQLMetric scan_numOutputRows;
/* 010 */   private org.apache.spark.sql.execution.metric.SQLMetric scan_scanTime;
/* 011 */   private long scan_scanTime1;
/* 012 */   private org.apache.spark.sql.execution.vectorized.ColumnarBatch scan_batch;
/* 013 */   private int scan_batchIdx;
/* 014 */   private org.apache.spark.sql.execution.vectorized.ColumnVector scan_colInstance0;
/* 015 */   private UnsafeRow scan_result;
/* 016 */   private org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder scan_holder;
/* 017 */   private org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter scan_rowWriter;
/* 018 */   private org.apache.spark.sql.execution.metric.SQLMetric filter_numOutputRows;
/* 019 */   private UnsafeRow filter_result;
/* 020 */   private org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder filter_holder;
/* 021 */   private org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter filter_rowWriter;
/* 022 */   private UnsafeRow project_result;
/* 023 */   private org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder project_holder;
/* 024 */   private org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter project_rowWriter;
/* 025 */
/* 026 */   public GeneratedIterator(Object[] references) {
/* 027 */     this.references = references;
/* 028 */   }
/* 029 */
/* 030 */   public void init(int index, scala.collection.Iterator[] inputs) {
/* 031 */     partitionIndex = index;
/* 032 */     this.inputs = inputs;
/* 033 */     scan_input = inputs[0];
/* 034 */     this.scan_numOutputRows = (org.apache.spark.sql.execution.metric.SQLMetric) references[0];
/* 035 */     this.scan_scanTime = (org.apache.spark.sql.execution.metric.SQLMetric) references[1];
/* 036 */     scan_scanTime1 = 0;
/* 037 */     scan_batch = null;
/* 038 */     scan_batchIdx = 0;
/* 039 */     scan_colInstance0 = null;
/* 040 */     scan_result = new UnsafeRow(1);
/* 041 */     this.scan_holder = new org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder(scan_result, 32);
/* 042 */     this.scan_rowWriter = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(scan_holder, 1);
/* 043 */     this.filter_numOutputRows = (org.apache.spark.sql.execution.metric.SQLMetric) references[2];
/* 044 */     filter_result = new UnsafeRow(1);
/* 045 */     this.filter_holder = new org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder(filter_result, 32);
/* 046 */     this.filter_rowWriter = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(filter_holder, 1);
/* 047 */     project_result = new UnsafeRow(1);
/* 048 */     this.project_holder = new org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder(project_result, 0);
/* 049 */     this.project_rowWriter = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(project_holder, 1);
/* 050 */
/* 051 */   }
/* 052 */
/* 053 */   private void scan_nextBatch() throws java.io.IOException {
/* 054 */     long getBatchStart = System.nanoTime();
/* 055 */     if (scan_input.hasNext()) {
/* 056 */       scan_batch = (org.apache.spark.sql.execution.vectorized.ColumnarBatch)scan_input.next();
/* 057 */       scan_numOutputRows.add(scan_batch.numRows());
/* 058 */       scan_batchIdx = 0;
/* 059 */       scan_colInstance0 = scan_batch.column(0);
/* 060 */
/* 061 */     }
/* 062 */     scan_scanTime1 += System.nanoTime() - getBatchStart;
/* 063 */   }
/* 064 */
/* 065 */   protected void processNext() throws java.io.IOException {
/* 066 */     if (scan_batch == null) {
/* 067 */       scan_nextBatch();
/* 068 */     }
/* 069 */     while (scan_batch != null) {
/* 070 */       int numRows = scan_batch.numRows();
/* 071 */       while (scan_batchIdx < numRows) {
/* 072 */         int scan_rowIdx = scan_batchIdx++;
/* 073 */         boolean scan_isNull = scan_colInstance0.isNullAt(scan_rowIdx);
/* 074 */         UTF8String scan_value = scan_isNull ? null : (scan_colInstance0.getUTF8String(scan_rowIdx));
/* 075 */
/* 076 */         if (!(!(scan_isNull))) continue;
/* 077 */
/* 078 */         boolean filter_isNull2 = false;
/* 079 */
/* 080 */         Object filter_obj = ((Expression) references[3]).eval(null);
/* 081 */         UTF8String filter_value4 = (UTF8String) filter_obj;
/* 082 */         boolean filter_value2 = false;
/* 083 */         filter_value2 = scan_value.equals(filter_value4);
/* 084 */         if (!filter_value2) continue;
/* 085 */
/* 086 */         filter_numOutputRows.add(1);
/* 087 */
/* 088 */         boolean project_isNull = false;
/* 089 */         int project_value = -1;
/* 090 */         if (!false) {
/* 091 */           try {
/* 092 */             project_value = scan_value.toInt();
/* 093 */           } catch (java.lang.NumberFormatException e) {
/* 094 */             project_isNull = true;
/* 095 */           }
/* 096 */
/* 097 */         }
/* 098 */         project_rowWriter.zeroOutNullBytes();
/* 099 */
/* 100 */         if (project_isNull) {
/* 101 */           project_rowWriter.setNullAt(0);
/* 102 */         } else {
/* 103 */           project_rowWriter.write(0, project_value);
/* 104 */         }
/* 105 */         append(project_result);
/* 106 */         if (shouldStop()) return;
/* 107 */       }
/* 108 */       scan_batch = null;
/* 109 */       scan_nextBatch();
/* 110 */     }
/* 111 */     scan_scanTime.add(scan_scanTime1 / (1000 * 1000));
/* 112 */     scan_scanTime1 = 0;
/* 113 */   }
/* 114 */ }
```
codegen part as above `scan_value` is a `UTF8String` and want to call toInt() method with zero parameters but only found `boolean toInt(IntWrapper intWrapper)`

**Comment by LuciferYang** [comment]
cc @jerrychenhf
